openapi: 3.0.0
info:
  title: Base API
  version: 1.0.0
  description: a simple API example

servers:
  - url: http://localhost:8080
    description: Local server

# tags:
#   - name: Health
#     description: Health check routes

paths:
  /health:
    get:
      # tags:
      #   - Health
      summary: health check route for discovery
      responses:
        '200':
          description: health check route
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Ok